name: No Longer In The Shadows
favicon: null
layout_spectrum: 0.8835475973319262
typography_spectrum: 0.25658270763233304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6694439435377717
  lightness: 0.6316024453844875
  saturation: 0.26355889113619924
  rhythmicContrast: 0.02168342680670321
purpose: []
